services:
  notificationdb:
    image: postgres:15-alpine
    container_name: notificationdb
    restart: always
    environment:
      POSTGRES_DB: notificationdb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5436:5432'
    volumes:
      - ./pg-data:/var/lib/postgresql/data

