server:
  port: 9000
  error:
    include-message: always
    include-stacktrace: never

spring:
  application:
    name: gateway-server

  output:
    ansi:
      enabled: ALWAYS

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka

logging:
  level:
    pl:
      dk:
        gateway_server: TRACE
logging.level.org.hibernate.orm.jdbc.bind: TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE