spring:
  application:
    name: notification-service
  profiles:
    active: dev

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka

scheduler:
 reminder:
   retry: 0 10 10-14 * * *
   clean: 0 10 1-2 * * *