spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:test

  docker:
    compose:
      enabled: false

  devtools:
    livereload:
      enabled: true
    add-properties: true







