services:
  carddb:
    image: postgres:15-alpine
    container_name: carddb
    restart: always
    environment:
      POSTGRES_DB: carddb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - ./pg-data:/var/lib/postgresql/data
