spring:
  application:
    name: EUREKA_SERVER
server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    pl:
      dk:
        eureka_server: TRACE