server:
  port: 8082
  error:
    include-message: always
    include-stacktrace: never

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:test

logging:
  level:
    pl:
      dk:
        UserService: TRACE