spring:
  application:
    name: exchange-service

  profiles:
    active: dev

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka

scheduler:
  update-currencies: 0 0 * * * *