server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: 

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
      open-in-view: false

  h2:
    console:
      enabled: true

  flyway:
    locations:
    - classpath:db/migration
    clean-disabled: false
    enabled: true
    execute-in-transaction: true

logging:
  level:
    pl:
      dk:
        UserService: TRACE
    org:
      flywaydb: TRACE
      hibernate:
        orm:
          jdbc:
            bind: TRACE
