services:
  loandb:
    image: 'postgres:latest'
    container_name: loandb
    restart: always
    environment:
      POSTGRES_DB: loandb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /pg-data
    ports:
      - '5435:5432'
    volumes:
      - ./pg-data:/pg-data

