services:
  loandb:
    image: postgres:15-alpine
    container_name: loandb
    restart: always
    environment:
      POSTGRES_DB: loandb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5435:5432'
    volumes:
      - ./pg-data:/var/lib/postgresql/data

