server:
  port: 8083
  error:
    include-message: always
    include-stacktrace: never

spring:
  config:
    activate:
      on-profile: dev
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:h2:mem:test

  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        retries: 3
        retry-backoff-ms: 5000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
      open-in-view: false

  flyway:
    locations:
      - classpath:db/migration
    clean-disabled: false
    enabled: true
    execute-in-transaction: true

logging:
  level:
    pl:
      dk:
        transfer_service: TRACe

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 2

