services:
  transferdb:
    image: postgres:15-alpine
    container_name: transferdb
    restart: always
    environment:
      POSTGRES_DB: transferdb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5437:5432'
    volumes:
      - ./pg-data:/var/lib/postgresql/data

