server:
  port: 9000
  error:
    include-message: always
    include-stacktrace: never

spring:
  config:
    activate:
      on-profile: dev

  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    pl:
      dk:
        gateway_server: TRACE
