spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/accountdb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  docker:
    compose:
      enabled: true
      stop:
        command: down
      skip:
        in-tests: true
      file: account-service/compose.yml

  devtools:
    livereload:
      enabled: false
