services:
  userdb:
    image: postgres:15-alpine
    container_name: userdb
    restart: always
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5438:5432'
    volumes:
      - ./pg-data:/var/lib/postgresql/data