spring:
  application:
    name: eureka-server

  docker:
    compose:
      enabled: true
      stop:
        command: down
      skip:
        in-tests: true
      file: eureka-server/compose.yml

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    pl:
      dk:
        eureka_server: TRACE