spring:
  application:
    name: LOAN-SERVICE

  profiles:
    active: dev

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka

scheduler:
  payment-status: 0 1 0 * * ?
