spring:
  application:
    name: loan-service

  profiles:
    active: dev

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka

scheduler:
  payment-status:
    overdue: 0 0/15 0-1 * * *
    pending: 0 0/15 2-3 * * *
    loan-payment: 0 0/15 4-5,22-23 * * *
    loan-schedule-reminder: 0 0 6 * * *