server:
  port: 8084
  error:
    include-message: always
    include-stacktrace: never

spring:
  config:
    activate:
      on-profile: dev
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:h2:mem:test

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
      open-in-view: false

  flyway:
    locations:
      - classpath:db/migration
    clean-disabled: false
    enabled: true
    execute-in-transaction: true

  modulith:
    events:
      republish-outstanding-events-on-restart: true
  h2:
    console:
      enabled: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        retries: 3
        retry-backoff-ms: 5000

    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
      group-id: loan-events-listener-group
    listener:
      concurrency: 3

logging:
  level:
    pl:
      dk:
        loan-service: TRACE

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 2

