services:
  accountdb:
    image: postgres:15-alpine
    container_name: accountdb
    restart: always
    environment:
      POSTGRES_DB: accountdb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./pg-data:/var/lib/postgresql/data