services:
  exchangedb:
    image: postgres:15-alpine
    container_name: exchangedb
    restart: always
    environment:
      POSTGRES_DB: exchangedb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5434:5432'
    volumes:
      - ./pg-data:/var/lib/postgresql/data
